### ISSUE TITLE
Can't see DynamoUtilities nodes

### ISSUE THREAD

**Issue by andydandy74** [redinkinc/DynamoUtilities#1]
I was just looking for the Dynamo Utilities node and I couldn't find them. I have the latest version installed (0.0.6) and I am running Dynamo 0.7.5 stable.

**Comment by redinkinc** [comment]
Thanks @andydandy74 for notification. Can you please have a look if you have a library called "DynamoCoreWpf.dll" somewhere in your Dynamo Installation folder. Seems that this library is missing in the 0.7.5 stable build but this is currently necessary to run Dynamo.Utilities.

**Comment by redinkinc** [comment]
Had a look on it. DynamoCoreWpf is intruduced in Dynamo 0.7.6. So Dynamo Utilities are not supported in earlier Versions...

**Comment by andydandy74** [comment]
It is indeed missing. Works fine in 0.8 ...
